### ISSUE TITLE
Runtime Error: No CUDA GPUs are avialable (even when GPU runtime is selected)

### ISSUE THREAD

**Issue by Tylersuard** [lucidrains/DALLE-pytorch#111]
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-9-f0f348328a8d> in <module>()
      7 
      8 images = np.stack(images).astype(float) / 255
----> 9 images = torch.from_numpy(images).to(torch.float32).permute(0, 3, 1, 2).cuda()

/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py in _lazy_init()
    168         # This function throws if there's a driver initialization error, no GPUs
    169         # are found or any other error occurs
--> 170         torch._C._cuda_init()
    171         # Some of the queued calls may reentrantly call _lazy_init();
    172         # we need to just return without initializing in that case.

RuntimeError: No CUDA GPUs are available

This happened after running the line:
images = torch.from_numpy(images).to(torch.float32).permute(0, 3, 1, 2).cuda()

in rainbow_dalle.ipynb colab.

**Comment by sorrge** [comment]
Please remove the line
```
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
from the beginning of the notebook, or select your GPUs there.

**Comment by Tylersuard** [comment]
Thank you!

**Comment by darshananimus** [comment]
i am not using a notebook how can i do this
on my ubuntu and i have the same error

**Comment by MartinJohannessen** [comment]
I don't have that line. I have the same error on my ubuntu on wsl2

**Comment by tanveer-hussain** [comment]
> Please remove the line
> 
> ```
> os.environ["CUDA_VISIBLE_DEVICES"] = "1"
> ```
> 
> from the beginning of the notebook, or select your GPUs there.

This works for me, I am on Windows 10 operating system with RTX 3090

**Comment by keat123** [comment]
I have the same error. I am working on colab and I don't have that line.  What to do?

**Comment by Khushi-Shah-1** [comment]
> I have the same error. I am working on colab and I don't have that line. What to do?

Hi, you found a solution?

**Comment by keerthisuresh01** [comment]
i have the same error working in google colab

**Comment by 2197808908a** [comment]
> > Please remove the line
> > ```
> > os.environ["CUDA_VISIBLE_DEVICES"] = "1"
> > ```

> > from the beginning of the notebook, or select your GPUs there.
> 
> This works for me, I am on Windows 10 operating system with RTX 3090
@tanveer-hussain 
Shouldn't it be os.environ["CUDA_VISIBLE_DEVICES"] = "0"?
