### ISSUE TITLE
Google Colab notebook needs updates

### ISSUE THREAD

**Issue by rvencu** [lucidrains/DALLE-pytorch#243]
Google Colab notebook has errors and even after fixing them the last cell throws cuda errors. Even copied to local installation the last cell breaks perhaps because of limited VRAM size.

**Comment by metaphorz** [comment]
Yes I get vae-final.pt created but then in the last cell, the error is: ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-8-7c274d6637cf> in <module>()
     19 
     20 from dalle_pytorch import OpenAIDiscreteVAE, DiscreteVAE, DALLE
---> 21 from dalle_pytorch.simple_tokenizer import tokenizer, HugTokenizer
     22 
     23 # helpers

ModuleNotFoundError: No module named 'dalle_pytorch.simple_tokenizer'

**Comment by rvencu** [comment]
I removed some of these basic errors, here is my last cell content. But the code breaks in cuda for some reason

`from random import choice
from pathlib import Path

# torch

import torch
from torch.optim import Adam
from torch.nn.utils import clip_grad_norm_

# vision imports

from PIL import Image
from torchvision import transforms as T
from torch.utils.data import DataLoader, Dataset
from torchvision.datasets import ImageFolder
from torchvision.utils import make_grid, save_image

# dalle related classes and utils

from dalle_pytorch import OpenAIDiscreteVAE, DiscreteVAE, DALLE
from dalle_pytorch.tokenizer import tokenizer, HugTokenizer

# helpers

def exists(val):
    return val is not None

# argument parsing

VAE_PATH = None   # './vae.pt' - will use OpenAIs pretrained VAE if not set
DALLE_PATH = None # './dalle.pt'
TAMING = False    # use VAE from taming transformers paper
IMAGE_TEXT_FOLDER = './'
BPE_PATH = None
RESUME = exists(DALLE_PATH)

EPOCHS = 20
BATCH_SIZE = 4
LEARNING_RATE = 3e-4
GRAD_CLIP_NORM = 0.5

MODEL_DIM = 512
TEXT_SEQ_LEN = 256
DEPTH = 2
HEADS = 4
DIM_HEAD = 64
REVERSIBLE = True
VOCAB_SIZE = 512

# tokenizer

if BPE_PATH is not None:
    tokenizer = HugTokenizer(BPE_PATH)

# reconstitute vae

if RESUME:
    dalle_path = Path(DALLE_PATH)
    assert dalle_path.exists(), 'DALL-E model file does not exist'

    loaded_obj = torch.load(str(dalle_path))

    dalle_params, vae_params, weights = loaded_obj['hparams'], loaded_obj['vae_params'], loaded_obj['weights']

    if vae_params is not None:
        vae = DiscreteVAE(**vae_params)
    else:
        vae = OpenAIDiscreteVAE()

    dalle_params = dict(        
        **dalle_params
    )

    IMAGE_SIZE = vae.image_size

else:
    if exists(VAE_PATH):
        vae_path = Path(VAE_PATH)
        assert vae_path.exists(), 'VAE model file does not exist'

        loaded_obj = torch.load(str(vae_path))

        vae_params, weights = loaded_obj['hparams'], loaded_obj['weights']

        vae = DiscreteVAE(**vae_params)
        vae.load_state_dict(weights)
    else:
        print('using pretrained VAE for encoding images to tokens')
        vae_params = None

        vae_klass = OpenAIDiscreteVAE if not TAMING else VQGanVAE1024
        vae = vae_klass()

    IMAGE_SIZE = vae.image_size

    dalle_params = dict(
        num_text_tokens = VOCAB_SIZE,
        text_seq_len = TEXT_SEQ_LEN,
        dim = MODEL_DIM,
        depth = DEPTH,
        heads = HEADS,
        dim_head = DIM_HEAD,
        reversible = REVERSIBLE
    )

# helpers

def save_model(path):
    save_obj = {
        'hparams': dalle_params,
        'vae_params': vae_params,
        'weights': dalle.state_dict()
    }

    torch.save(save_obj, path)

# dataset loading

class TextImageDataset(Dataset):
    def __init__(self, folder, text_len = 256, image_size = 128):
        super().__init__()
        path = Path(folder)

        text_files = [*path.glob('**/*.txt')]

        image_files = [
            *path.glob('**/*.png'),
            *path.glob('**/*.jpg'),
            *path.glob('**/*.jpeg')
        ]

        text_files = {t.stem: t for t in text_files}
        image_files = {i.stem: i for i in image_files}

        keys = (image_files.keys() & text_files.keys())

        self.keys = list(keys)
        self.text_files = {k: v for k, v in text_files.items() if k in keys}
        self.image_files = {k: v for k, v in image_files.items() if k in keys}

        self.image_tranform = T.Compose([
            T.Lambda(lambda img: img.convert('RGB') if img.mode != 'RGB' else img),
            T.RandomResizedCrop(image_size, scale = (0.75, 1.), ratio = (1., 1.)),
            T.ToTensor()
        ])

    def __len__(self):
        return len(self.keys)

    def __getitem__(self, ind):
        key = self.keys[ind]
        text_file = self.text_files[key]
        image_file = self.image_files[key]

        image = Image.open(image_file)
        descriptions = text_file.read_text().split('\n')
        descriptions = list(filter(lambda t: len(t) > 0, descriptions))
        description = choice(descriptions)

        tokenized_text = tokenizer.tokenize(description).squeeze(0)
        mask = tokenized_text != 0

        image_tensor = self.image_tranform(image)
        return tokenized_text, image_tensor, mask

# create dataset and dataloader

ds = TextImageDataset(
    IMAGE_TEXT_FOLDER,
    text_len = TEXT_SEQ_LEN,
    image_size = IMAGE_SIZE
)

assert len(ds) > 0, 'dataset is empty'
print(f'{len(ds)} image-text pairs found for training')

dl = DataLoader(ds, batch_size = BATCH_SIZE, shuffle = True, drop_last = True)

# initialize DALL-E

dalle = DALLE(vae = vae, **dalle_params).cuda()

if RESUME:
    dalle.load_state_dict(weights)

# optimizer

opt = Adam(dalle.parameters(), lr = LEARNING_RATE)

# experiment tracker

import wandb

model_config = dict(
    depth = DEPTH,
    heads = HEADS,
    dim_head = DIM_HEAD
)

run = wandb.init(project = 'dalle_train_transformer', resume = RESUME, config = model_config)

# training

for epoch in range(EPOCHS):
    for i, (text, images, mask) in enumerate(dl):
        text, images, mask = map(lambda t: t.cuda(), (text, images, mask))

        loss = dalle(text, images, mask = mask, return_loss = True)

        loss.backward()
        clip_grad_norm_(dalle.parameters(), GRAD_CLIP_NORM)

        opt.step()
        opt.zero_grad()

        log = {}

        if i % 10 == 0:
            print(epoch, i, f'loss - {loss.item()}')

            log = {
                **log,
                'epoch': epoch,
                'iter': i,
                'loss': loss.item()
            }

        if i % 100 == 0:
            sample_text = text[:1]
            token_list = sample_text.masked_select(sample_text != 0).tolist()
            decoded_text = tokenizer.decode(token_list)

            image = dalle.generate_images(
                text[:1],
                mask = mask[:1],
                filter_thres = 0.9    # topk sampling at 0.9
            )

            save_model(f'./dalle.pt')
            wandb.save(f'./dalle.pt')

            log = {
                **log,
                'image': wandb.Image(image, caption = decoded_text)
            }

        wandb.log(log)

    # save trained model to wandb as an artifact every epoch's end

    model_artifact = wandb.Artifact('trained-dalle', type = 'model', metadata = dict(model_config))
    model_artifact.add_file('dalle.pt')
    run.log_artifact(model_artifact)

save_model(f'./dalle-final.pt')
wandb.save('./dalle-final.pt')
model_artifact = wandb.Artifact('trained-dalle', type = 'model', metadata = dict(model_config))
model_artifact.add_file('dalle-final.pt')
run.log_artifact(model_artifact)

wandb.finish()`

**Comment by nostalgebraist** [comment]
The CUDA error happens when the tokenizer produces indices that are too big for the text embedding.  This fixes it:

```python
VOCAB_SIZE = tokenizer.vocab_size
```

**Comment by metaphorz** [comment]
Added this and re-ran but end up with (after training):

 

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-10-38bbbacb682b> in <module>()

     19 

     20 from dalle_pytorch import OpenAIDiscreteVAE, DiscreteVAE, DALLE

---> 21 from dalle_pytorch.simple_tokenizer import tokenizer, HugTokenizer

     22 

     23 # helpers

 

ModuleNotFoundError: No module named 'dalle_pytorch.simple_tokenizer'

 

 

-p

 

 

From: nostalgebraist ***@***.***>
Reply-To: lucidrains/DALLE-pytorch ***@***.***>
Date: Wednesday, May 19, 2021 at 2:54 PM
To: lucidrains/DALLE-pytorch ***@***.***>
Cc: Paul Fishwick ***@***.***>, Comment ***@***.***>
Subject: Re: [lucidrains/DALLE-pytorch] Google Colab notebook needs updates (#243)

 

The CUDA error happens when the tokenizer produces indices that are too big for the text embedding. This fixes it:

VOCAB_SIZE = tokenizer.vocab_size

**Comment by rvencu** [comment]
the file name changed so the line became 

```from dalle_pytorch.tokenizer import tokenizer, HugTokenizer```

I posted the entire cell to overwrite the old one...

**Comment by rvencu** [comment]
> The CUDA error happens when the tokenizer produces indices that are too big for the text embedding. This fixes it:
> 
> ```python
> VOCAB_SIZE = tokenizer.vocab_size
> ```

Yes, I confirm it works since my error changed to something more clear:

```CUDA out of memory. Tried to allocate 1.10 GiB (GPU 0; 8.00 GiB total capacity; 3.91 GiB already allocated; 787.33 MiB free; 5.26 GiB reserved in total by PyTorch)```

**Comment by metaphorz** [comment]
Richard I had edited the colab notebook before. Is the notebook updated? If so, I’ll Erase the old notebook. Otherwise I’ll manually edit. Or perhaps it was a GitHub change? Still a newbie on colab.

-p

Paul Fishwick, PhD
Distinguished University Chair of Arts, Technology, and Emerging Communication
Professor of Computer Science
Director, Creative Automata Laboratory
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick
Media: ***@***.***
Modeling: digest.sigsim.org
Twitter: @PaulFishwick

**Comment by rvencu** [comment]
This colab (second one from readme.md) is not updated and I believe only the author can make permanent changes there.
https://colab.research.google.com/drive/1dWvA54k4fH8zAmiix3VXbg95uEIMfqQM?usp=sharing

My errors appear in local environment since my GPU only has 8GB of VRAM. I would say code is correct (my last cell posted above with the VOCAB_SIZE line in addition).

**Comment by metaphorz** [comment]
I still had issues, but this one raised my hopes. It uses the trained model and produces

a set of birds according to the text.

 

Only issue is that you need to install clip, so I added a cell !pip install clip

and then the notebook worked fine

 

https://github.com/kobiso/DALLE-reproduction

 

-p

 

Paul Fishwick, PhD
Distinguished University Chair of Arts, Technology, and Emerging Communication
Professor of Computer Science
Director, Creative Automata Laboratory
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick
Media: ***@***.***
Modeling: digest.sigsim.org
Twitter: @PaulFishwick

ONLINE: Webex,Collaborate, TEAMS, Zoom, Skype, Hangout

 

 

From: Richard Vencu ***@***.***>
Reply-To: lucidrains/DALLE-pytorch ***@***.***>
Date: Thursday, May 20, 2021 at 12:17 PM
To: lucidrains/DALLE-pytorch ***@***.***>
Cc: Paul Fishwick ***@***.***>, Comment ***@***.***>
Subject: Re: [lucidrains/DALLE-pytorch] Google Colab notebook needs updates (#243)

 

This colab (second one from readme.md) is not updated and I believe only the author can make permanent changes there.
https://colab.research.google.com/drive/1dWvA54k4fH8zAmiix3VXbg95uEIMfqQM?usp=sharing

My errors appear in local environment since my GPU only has 8GB of VRAM. I would say code is correct (my last cell posted above with the VOCAB_SIZE line in addition).

**Comment by afiaka87** [comment]
addressed here https://github.com/lucidrains/DALLE-pytorch/pull/320
