### ISSUE TITLE
CUDA error trying to run on a simple dataset

### ISSUE THREAD

**Issue by TheodoreGalanos** [lucidrains/DALLE-pytorch#65]
Hello! 

I am finally trying to train dall-e, using the provided OAI pretrained vqvae model as it is provided in the repo.

I am using the standard code provided and feeding my dataset in the way requested (pairs of images and text). The only things I changed were the dall-e settings:

```
dalle = DALLE(
    dim = 1024,
    vae = vae,                  # automatically infer (1) image sequence length and (2) number of image tokens
    num_text_tokens = 10000,    # vocab size for text
    text_seq_len = 256,         # text sequence length
    depth = 16,                  # should aim to be 64
    heads = 16,                 # attention heads
    dim_head = 64,              # attention head dimension
    attn_dropout = 0.1,         # attention dropout
    ff_dropout = 0.1            # feedforward dropout
).cuda()
```

My image size is also 256x256. I am trying to run this on Colab Pro. I am getting 2 errors, the first one is the following:

![image](https://user-images.githubusercontent.com/13436572/110126645-97180b80-7dff-11eb-8288-4f05614b053d.png)

and after rerunning the training code, I get a CUDA assertion:

![image](https://user-images.githubusercontent.com/13436572/110126691-a434fa80-7dff-11eb-8ee2-9a9d470e339c.png)

I tried to search and debug it but it seems a rather obscure error, I wonder if some dimension is off or invalid smh in the model? Would love your thoughts and also if I missed something obvious!

Thanks for all your incredible work!

Best,
Theodore.

**Comment by lucidrains** [comment]
@TheodoreGalanos Hi Theodore! Thank for trying it out! I've added an extra check to make sure you are passing in the correct image https://github.com/lucidrains/DALLE-pytorch/releases/tag/0.2.4 Could you possibly upgrade and see if your script still runs?

**Comment by TheodoreGalanos** [comment]
Thanks @lucidrains apologies I missed this been hectic few days. Will try tonight and let you know here asap.

**Comment by TheodoreGalanos** [comment]
Thank you! That fixed it! Apologies for not being careful when trying to train with the pretrained model, I totally ignored the default parameters I needed to use.
